### ISSUE TITLE
Cannot enable plugin on mac m1

### ISSUE THREAD

**Issue by JeFawk** [paulloz/godot-ink#56] opened 2023-07-28 22:09 UTC
**Describe the bug**
Plugin can be installed from Assets Lib but cannot be enabled. When trying to enable it, this error occurs:
<img width="779" alt="image" src="https://github.com/paulloz/godot-ink/assets/7268697/a16dfc02-a663-4537-89aa-5c4a3d97da27">

**To Reproduce**
1. create a new project using graphics "Mobile" on an m1 mac
2. install the plugin from the AssetLib
3. try to enable plugin
4. notice the error

**Environment**
* OS: MacBook Air M1
* Godot version: 4.1.1
* godot-ink version: latest from the Assets Library: 

<img width="273" alt="image" src="https://github.com/paulloz/godot-ink/assets/7268697/6d4bcb3a-bae0-4ff6-951a-c33e4ba9c5b0">

* ink version: 

**Additional context**

**Comment by paulloz** [comment] 2023-07-28 22:48
This feels like a duplicate of #57.

**Closed** 2023-07-28 22:48 UTC
Labels: bug, duplicate
